small change

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -98,19 +98,19 @@ steps:
           echo "Production smoke test passed successfully with status code: $$STATUS_CODE"
         fi
 
-  - name: 'gcr.io/cloud-builders/docker'
-    id: 'Cleanup local Docker images'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
+  # - name: 'gcr.io/cloud-builders/docker'
+  #   id: 'Cleanup local Docker images'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       set -e
 
-        echo "----------------------------------------------------------------------------------------------------------"
-        echo "Cleaning up local Docker images to free space"
-        echo "----------------------------------------------------------------------------------------------------------"
+  #       echo "----------------------------------------------------------------------------------------------------------"
+  #       echo "Cleaning up local Docker images to free space"
+  #       echo "----------------------------------------------------------------------------------------------------------"
 
-        docker rmi ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG} || true
+  #       docker rmi ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG} || true
        
 
 logsBucket: 'gs://${_LOG_BUCKET}'
