add health check

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,10 +1,3 @@
-# substitutions:
-#   _REGION: 'us-east1'
-#   _REPOSITORY: 'docker-repo'
-#   _IMAGE: 'nginx-app'
-#   _LOG_BUCKET: 'devops_ci_logs'
-#   _TAG: 'v1.0.1'
-
 steps:
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     id: 'apply-and-deploy'
@@ -82,9 +75,9 @@ steps:
 
         # 1. Fetch production URL
 
-        echo "Fetching production URL from us-east1"
+        echo "Fetching production URL from ${_REGION}"
         PROD_URL=$(gcloud run services describe nginx-prod \
-          --region=us-east1 \
+          --region=${_REGION} \
           --format='value(status.url)')
 
         echo "Testing URL: $$PROD_URL"
@@ -99,19 +92,21 @@ steps:
           echo "Production smoke test passed successfully with status code: $$STATUS_CODE"
         fi
 
-  - name: 'gcr.io/cloud-builders/docker'
-    id: 'Cleanup local Docker images'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
+        # 3. Health check for 60 seconds to ensure the service is stable
 
-        echo "----------------------------------------------------------------------------------------------------------"
-        echo "Cleaning up local Docker images to free space"
-        echo "----------------------------------------------------------------------------------------------------------"
+        echo "Checking $$PROD_URL/health"
 
-        docker rmi ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG} || true
-       
+          for i in {1..10}; do
+            if curl -fsS "$$PROD_URL/health"; then
+              echo "Health check passed"
+              exit 0
+            fi
+
+            echo "Waiting..."
+            sleep 10
+          done
+
+          echo "Health check failed"
+          exit 1
 
 logsBucket: 'gs://${_LOG_BUCKET}'
